POST  http://localhost:5291/api/create-role
###

POST http://localhost:5291/api/assign-role
###

POST http://localhost:5291/api/add-claim
###

POST http://localhost:5291/api/login
###

GET http://localhost:5291/
###

GET http://localhost:5291/api/admin-only
Cookie: .AspNetCore.Identity.Application=CfDJ8JDIKhQJQg1Jq_Pt3bTnvMshiWie_uaM8GVYYoIst_YJ1SIoln57TMnEJARPVN2_rhEhm2WrQnBOpPNMd8Ufu9hk2WBlwS6FjKcSJOiTytCIlIVws5iiwNoMlrgd3_nwHwidXecrgSGbw1ge-39vB7DAcNWBX5-IUQFqY1nhKNrC2a8z8fiYFl1FBe4d6rZkBW-jvAZask2OWDnLiq_Trh39BMDFk6lj25qT9yU63DvtfGR6Rbp1KYmLcTy5sn0zP6S77l_yh0PfqQeaz3djxYjoUxYC6wajgHGyDFeS6XXTNbfegxqXAoTNf8kIbYq9ciyUe3CQ7G7_hCzqPa7KA4iMaV7wJ9moJO8A0wNoNmp9P3cunUYgCof4V0sDv5cfJ5aSAyg09h3DGN5D7dxYXgcNbDHHhFNR60dyUGh4aRrqjtHRwb8Qon3euqIMvEXvF0i24WT3zMhJetunrQEw9VS5CFgv8ql5EfK8i5qfu4r1oGqY-ggbq15tjWYIXL0HBR1DAqn3WSxJwf0EV0Q3eB9_NXQUSZb7pZV38lRjRF4eaFBpavuWL9dnfBHybfbKXKRmVBOxz6_0cmRp9ahgWyxpnyqPm4PfooosoQx-fjTJ5EkofH9BX4qUy1TjqX2GD0g3PSsr-lAFbe2cVckoaaqvATLC6RII6VAvBsNQIsjtI5kdY0R5ldbEnLQUWn4Qa4i-Qu3BSojIhcoWBnM6laPjlixXxbUCBdA5poRIS5rlo0vTxDL19PlrzN5E-fTc2m-Uy6jD4WrHri7yq3_cc-NTO9pIGRFYQP9tMV077Xxw8QJ2NwL-IXT_Mdl5s04sIO0B-zG-Jje8n9ZfAGZk5L5WpEdnbpInrVdKWLsZeWfz; path=/; samesite=lax; httponly
###

GET http://localhost:5291/api/user-claim-check
Cookie: .AspNetCore.Identity.Application=CfDJ8JDIKhQJQg1Jq_Pt3bTnvMshiWie_uaM8GVYYoIst_YJ1SIoln57TMnEJARPVN2_rhEhm2WrQnBOpPNMd8Ufu9hk2WBlwS6FjKcSJOiTytCIlIVws5iiwNoMlrgd3_nwHwidXecrgSGbw1ge-39vB7DAcNWBX5-IUQFqY1nhKNrC2a8z8fiYFl1FBe4d6rZkBW-jvAZask2OWDnLiq_Trh39BMDFk6lj25qT9yU63DvtfGR6Rbp1KYmLcTy5sn0zP6S77l_yh0PfqQeaz3djxYjoUxYC6wajgHGyDFeS6XXTNbfegxqXAoTNf8kIbYq9ciyUe3CQ7G7_hCzqPa7KA4iMaV7wJ9moJO8A0wNoNmp9P3cunUYgCof4V0sDv5cfJ5aSAyg09h3DGN5D7dxYXgcNbDHHhFNR60dyUGh4aRrqjtHRwb8Qon3euqIMvEXvF0i24WT3zMhJetunrQEw9VS5CFgv8ql5EfK8i5qfu4r1oGqY-ggbq15tjWYIXL0HBR1DAqn3WSxJwf0EV0Q3eB9_NXQUSZb7pZV38lRjRF4eaFBpavuWL9dnfBHybfbKXKRmVBOxz6_0cmRp9ahgWyxpnyqPm4PfooosoQx-fjTJ5EkofH9BX4qUy1TjqX2GD0g3PSsr-lAFbe2cVckoaaqvATLC6RII6VAvBsNQIsjtI5kdY0R5ldbEnLQUWn4Qa4i-Qu3BSojIhcoWBnM6laPjlixXxbUCBdA5poRIS5rlo0vTxDL19PlrzN5E-fTc2m-Uy6jD4WrHri7yq3_cc-NTO9pIGRFYQP9tMV077Xxw8QJ2NwL-IXT_Mdl5s04sIO0B-zG-Jje8n9ZfAGZk5L5WpEdnbpInrVdKWLsZeWfz; path=/; samesite=lax; httponly
###

